apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "deploy-jobs.name" . }}
  labels:
    {{- include "deploy-jobs.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ include "deploy-jobs.name" . }}
        image: "{{ .Values.image }}"
        envFrom:
        - configMapRef:
            name: {{ include "deploy-jobs.name" . }}-env
      restartPolicy: {{ .Values.restartPolicy | default "Never" }}
  backoffLimit: {{ .Values.backoffLimit | default 0 }}