apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-deployments.name" . }}
  labels:
    {{- include "go-deployments.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "go-deployments.selectorLabels" . | nindent 4 }}
